version: 2.1

jobs:
  test:
    docker:
      - image: cimg/php:8.1.28-node
        environment:
          DB_HOST: 127.0.0.1
      - image: circleci/mysql:8.0
    working_directory: ~/laravelgram
    environment:
      DB_CONNECTION: testing
      DB_DATABASE: laravelgram_test_db
      DB_USERNAME: root
      DB_PASSWORD: ""
      DB_PORT: 3306
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_ROOT_PASSWORD: ""
      LARAVEL_BYPASS_ENV_CHECK: 1
    steps:
      - checkout
      - run:
          name: install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.3.0
      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:3306 -timeout 1m
      - run:
          name: Update apt-get
          command: |
            sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E88979FB9B30ACF2
            sudo apt-get update --allow-releaseinfo-change
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.json" }}
            - v1-dependencies-
      - run:
          name: Install PHP libraries
          command: composer install
      - save_cache:
          paths:
            - vendor
          key: v1-dependencies-{{ checksum "composer.json" }}
      - run:
          name: NPM install
          command: |
            npm ci
            npm run build
      - run:
          name: Run PHPUnit
          command: |
            php artisan migrate --env=testing --force
            php artisan test

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
  approve_merge:
    jobs:
      - hold:
          type: approval
          requires:
            - test
          filters:
            branches:
              only:
                - main
