version: 2.1

jobs:
  build:
    docker:
      - image: cimg/php:8.3.4
        environment:
          APP_ENV: testing
          MYSQL_HOST: 127.0.0.1
          MYSQL_PORT: 3306
          MYSQL_DATABASE: laravelgram_test_db
          MYSQL_USERNAME: "root"
          MYSQL_PASSWORD: ""
      - image: circleci/mysql:8.0
        environment:
          MYSQL_DATABASE: laravelgram_test_db
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_ROOT_HOST: "%"
    environment:
      DB_CONNECTION: testing
    working_directory: ~/laravelgram
    steps:
      - checkout
      - run:
          name: Update apt-get
          command: |
            sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E88979FB9B30ACF2
            sudo apt-get update --allow-releaseinfo-change
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.json" }}
            - v1-dependencies-
      - run:
          name: Install PHP libraries
          command: composer install
      - run:
          name: Create database and Run migrate
          command: |
            sudo apt-get update
            sudo apt-get dist-upgrade
            sudo apt-get install -y mysql-server mysql-client
            sudo service mysql start
            mysql -h 127.0.0.1 -u root -e "CREATE DATABASE IF NOT EXISTS laravelgram_test_db;"
            php artisan migrate --env=testing
      - save_cache:
          paths:
            - vendor
          key: v1-dependencies-{{ checksum "composer.json" }}
      - run:
          name: Run PHPUnit
          command: php artisan test
