version: 2.1

jobs:
  build:
    docker:
      - image: cimg/php:8.3.4
        environment:
          - DB_HOST: 127.0.0.1
      - image: circleci/mysql:8.0
    working_directory: ~/laravelgram
    environment:
      - APP_ENV: testing
      - DB_CONNECTION: testing
      - MYSQL_ALLOW_EMPTY_PASSWORD: true
    steps:
      - checkout
      - run:
          name: Update apt-get
          command: |
            sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E88979FB9B30ACF2
            sudo apt-get update --allow-releaseinfo-change
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.json" }}
            - v1-dependencies-
      - run:
          name: Install PHP libraries
          command: composer install
      - save_cache:
          paths:
            - vendor
          key: v1-dependencies-{{ checksum "composer.json" }}
      - run:
          name: install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.3.0
      - run:
          name: Run PHPUnit
          command: |
            php artisan migrate
            vendor/bin/phpunit
