version: 2.1
jobs:
  build:
    docker:
      - image: cimg/php:8.3.4
      - image: cimg/mysql:8.0
    environment:
      DB_CONNECTION: testing
      LARAVEL_BYPASS_ENV_CHECK: "1" # Set LARAVEL_BYPASS_ENV_CHECK to bypass environment check
    steps:
      - checkout
      - run:
          name: Docker php extensions install
          command: sudo docker-php-ext-install pdo_mysql
      - run:
          name: install PHP libraries
          command: composer install
      - run:
          name: Install Node.js and npm
          command: |
            curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
            sudo apt-get install -y nodejs
      - run:
          name: build vite
          command: |
            npm install
            npm run dev
      - run:
          name: Setup MySQL and Laravel
          command: |
            mysql -u root -e 'CREATE DATABASE laravel_test;'
            php artisan migrate --env=testing
      - run:
          name: Run PHPUnit
          command: php artisan test
